export default {
  today: [
    {
      summary: 'Clear',
      temperatureHi: 11,
      temperatureLow: 7,
      windSpeed: 9,
      windDirection: 'N',
      humidity: 71,
      icons: ['sun'],
    },
    {
      summary: 'Clear',
      temperatureHi: 14,
      temperatureLow: 12,
      windSpeed: 9,
      windDirection: 'N',
      humidity: 50,
      icons: ['sun', 'cloud'],
    },
    {
      summary: 'Overcast',
      temperatureHi: 13,
      temperatureLow: 12,
      windSpeed: 6,
      windDirection: 'N',
      humidity: 53,
      icons: ['cloud', 'rain'],
    },
    {
      summary: 'Overcast',
      temperatureHi: 11,
      temperatureLow: 9,
      windSpeed: 6,
      windDirection: 'N',
      humidity: 65,
      icons: ['cloud', 'moon', 'snow'],
    },
  ],
  tomorrow: [
    {
      summary: 'Overcast',
      temperatureHi: 13,
      temperatureLow: 7,
      windSpeed: 10,
      windDirection: 'N',
      humidity: 72,
      icons: ['cloud'],
    },
    {
      summary: 'Mostly Cloudy',
      temperatureHi: 18,
      temperatureLow: 14,
      windSpeed: 16,
      windDirection: 'N',
      humidity: 50,
      icons: ['cloud'],
    },
    {
      summary: 'Breezy and Partly Cloudy',
      temperatureHi: 16,
      temperatureLow: 11,
      windSpeed: 17,
      windDirection: 'N',
      humidity: 55,
      icons: ['cloud'],
    },
    {
      summary: 'Mostly Cloudy',
      temperatureHi: 10,
      temperatureLow: 10,
      windSpeed: 14,
      windDirection: 'N',
      humidity: 65,
      icons: ['cloud', 'moon'],
    },
  ],
};
